#include "PlaneToPBRTextureRoles.h"

namespace PlaneToPBRTextureRoles
{
	// Static configurations for each supported texture role
	static const FPlaneToPBRTextureRoleInfo BaseColorInfo = {
		EPlaneToPBRTextureRole::BaseColor,
		TEXT("basecolor"),
		TEXT("T_BaseColor"),
		true,               // bSRGB enabled for diffuse color
		TC_Default,
		SAMPLERTYPE_Color
	};

	static const FPlaneToPBRTextureRoleInfo DepthInfo = {
		EPlaneToPBRTextureRole::Depth,
		TEXT("depth"),
		TEXT("T_Depth"),
		false,              // Linear data
		TC_Grayscale,
		SAMPLERTYPE_LinearGrayscale
	};

	static const FPlaneToPBRTextureRoleInfo NormalInfo = {
		EPlaneToPBRTextureRole::Normal,
		TEXT("normal"),
		TEXT("T_Normal"),
		false,              // Linear normal map
		TC_Normalmap,
		SAMPLERTYPE_Normal
	};

	static const FPlaneToPBRTextureRoleInfo RoughnessInfo = {
		EPlaneToPBRTextureRole::Roughness,
		TEXT("roughness"),
		TEXT("T_Roughness"),
		false,              // Linear roughness data
		TC_Grayscale,
		SAMPLERTYPE_LinearGrayscale
	};

	static const FPlaneToPBRTextureRoleInfo MaskInfo = {
		EPlaneToPBRTextureRole::Mask,
		TEXT("mask"),
		TEXT("T_Mask"),
		false,              // Linear mask data
		TC_Grayscale,
		SAMPLERTYPE_LinearGrayscale
	};

	static const FPlaneToPBRTextureRoleInfo UnknownInfo;
}

const TArray<EPlaneToPBRTextureRole>& FPlaneToPBRTextureRoles::GetRequiredDownloadedRoles()
{
	// Roles generated by the Hugging Face server (BaseColor is imported from source file)
	static const TArray<EPlaneToPBRTextureRole> RequiredDownloadedRoles = {
		EPlaneToPBRTextureRole::Depth,
		EPlaneToPBRTextureRole::Normal,
		EPlaneToPBRTextureRole::Roughness,
		EPlaneToPBRTextureRole::Mask
	};
	return RequiredDownloadedRoles;
}

const FPlaneToPBRTextureRoleInfo& FPlaneToPBRTextureRoles::GetInfo(const EPlaneToPBRTextureRole Role)
{
	switch (Role)
	{
	case EPlaneToPBRTextureRole::BaseColor:
		return PlaneToPBRTextureRoles::BaseColorInfo;
	case EPlaneToPBRTextureRole::Depth:
		return PlaneToPBRTextureRoles::DepthInfo;
	case EPlaneToPBRTextureRole::Normal:
		return PlaneToPBRTextureRoles::NormalInfo;
	case EPlaneToPBRTextureRole::Roughness:
		return PlaneToPBRTextureRoles::RoughnessInfo;
	case EPlaneToPBRTextureRole::Mask:
		return PlaneToPBRTextureRoles::MaskInfo;
	default:
		return PlaneToPBRTextureRoles::UnknownInfo;
	}
}

EPlaneToPBRTextureRole FPlaneToPBRTextureRoles::FromKey(const FString& Key)
{
	const FString NormalizedKey = Key.ToLower();
	for (const EPlaneToPBRTextureRole Role : {
		EPlaneToPBRTextureRole::BaseColor,
		EPlaneToPBRTextureRole::Depth,
		EPlaneToPBRTextureRole::Normal,
		EPlaneToPBRTextureRole::Roughness,
		EPlaneToPBRTextureRole::Mask
	})
	{
		if (NormalizedKey == GetInfo(Role).Key)
		{
			return Role;
		}
	}

	return EPlaneToPBRTextureRole::Unknown;
}

EPlaneToPBRTextureRole FPlaneToPBRTextureRoles::FromImportedAssetName(const FString& AssetName)
{
	for (const EPlaneToPBRTextureRole Role : {
		EPlaneToPBRTextureRole::BaseColor,
		EPlaneToPBRTextureRole::Depth,
		EPlaneToPBRTextureRole::Normal,
		EPlaneToPBRTextureRole::Roughness,
		EPlaneToPBRTextureRole::Mask
	})
	{
		if (AssetName == GetInfo(Role).AssetName)
		{
			return Role;
		}
	}

	return EPlaneToPBRTextureRole::Unknown;
}
